### PR TITLE
Administration-upgrade

### PR DESCRIPTION
**Pull request by July-liu**
### Motivation

Translate administration-upgrade file

### Modifications

Update the translation schedule
To check the translated file, refer to https://crowdin.com/translate/apache-pulsar/768/en-zhcn#158642

### CODE REVIEW

**Comment by SylviaBABY** [comment]
@Jennifer88huang pls review and approve

**Comment by Jennifer88huang** [comment]
@July-liu Thank you very much for your contribution.
When you translate, follow the ]translation guidelines](https://github.com/apache/pulsar-translation#guidelines) strictly, which will improve translating and reviewing efficiency.
You need to pay special attention to the following guidelines:
- Add a space between English and Chinese characters
- Add a period at the end of sentences.
- Avoid using "请“ in technical writing and translation.
- Adjust translation, and make it easy to read and understand. (在理解正确的基础上，注意调整语序，读起来像是直接用中文写的，而不是翻译过来的）。

**Comment by July-liu** [comment]
@Jennifer88huang Thank you for your advices.

**Comment by July-liu** [comment]
@Jennifer88huang Thank you for your suggestions.

**Comment by sijia-w** [comment]
@Jennifer88huang We no longer have the schedule named as `schedule.md` now. I do not have write access to this pr. Can you help with the conflicts?

**Comment by Jennifer88huang** [comment]
@July-liu @sijia-w do you mind adding the changes in the [schedule_zh-CN.md](https://github.com/apache/pulsar-translation/blob/master/schedule_zh-CN.md) file. Thank you.

**Comment by Jennifer88huang** [comment]
Since there is conflict in this PR, I close it.
@July-liu feel free to open a new PR in the schedule_zh-CN.md file, thank you.

**Pull request closed without merging**
