### PR TITLE
functions-deploy: sijia-w

### PR DESCRIPTION
**Pull request by sijia-w**
### Motivation
Translate `functions-deploy` file.

### Modifications
Update the translation schedule.
To check the translated file, refer to https://crowdin.com/translate/apache-pulsar/778/en-zhcn

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@sijia-w Thank you very much for your contribution. 
1. Could you please delete the `.Rhistory` file? 
2. Keep only useful info in the PR description.

**Comment by Jennifer88huang** [comment]
1. Pulsar Functions is a proper noun in "Apache Pulsar" project, so you do not need to translate it. For other proper nouns, refer to https://shimo.im/sheets/5jozGy5WIUQQf5JV/MODOC. You can find the resources at https://github.com/apache/pulsar-translation#%E7%BF%BB%E8%AF%91
2. When you're not sure sth, you can refer to Pulsar website for general info, and then conduct translation.
image

**Comment by sijia-w** [comment]
Thank you for reminding me.
I changed the translation after I noticed that function is always a proper name. But, the file in my computer has no order mistake. I have no idea how it happened.

**Comment by Jennifer88huang** [comment]
@SylviaBABY could you please help her on this?

**Comment by SylviaBABY** [comment]
@sijia-w 上边提到的就是两个问题：
1.你提的这个pr里应该只有 schedule.md 这个文档，不应该出现这个
image
2.你文档中翻译的有个问题。应该翻译成：可以在 kube、amazon等进行部署xxxx，你翻译成了在
image
然后 Jennifer 已经在 crowdin 的翻译页面给你留言了，你可以去看一下～修改一下就可以。

针对问题1，如果你这个 pr 是在网页端提交的，那你可能需要把这个PR关闭然后重新提交一个只有md 文件的PR；如果你的PR是在本地进行提交的，那你直接去电脑里此repo库的文件夹里删除那个额外的文件即可。

**Comment by sijia-w** [comment]
Sylvia,
感谢你给出的详细解答。
1. 我已经在本地将 .Rhistory 文件删除；
2. 关于翻译的问题，我进入 crowdin 网页看到的翻译仍然是正常语序的

[image: WeChatd4cf4cf0032e2966caf7fca369084c05.png]
谢谢！

**Pull request closed without merging**
