### PR TITLE
Trans docs

### PR DESCRIPTION
**Pull request by sijia-w**
### Motivation

· make the doc more easily to understand

### Modifications

· add translated files

### CODE REVIEW

**Comment by Jennifer88huang** [comment]
@sijia-w which one will you finish this week? Please add the translation link in the description when pull request. Thank you.

**Comment by sijia-w** [comment]
All the files above were translated. Please check.
https://crowdin.com/translate/apache-pulsar/658/en-zhcn
https://crowdin.com/translate/apache-pulsar/772/en-zhcn
https://crowdin.com/translate/apache-pulsar/778/en-zhcn
https://crowdin.com/translate/apache-pulsar/92/en-zhcn
https://crowdin.com/translate/apache-pulsar/932/en-zhcn

Thank you.

**Comment by Jennifer88huang** [comment]
@Anonymitaet could you please help check and give feedback? Thank you.

**Comment by Anonymitaet** [comment]
@sijia-w I've reviewed `https://crowdin.com/translate/apache-pulsar/658/en-zhcn`. 
Could you please re-translate the segments that I do not approve? (I've commented in Crowdin as well)

**Pull request closed without merging**
