### PR TITLE
[Update] trans schedule

### PR DESCRIPTION
**Pull request by SylviaBABY**
## Motivation

*Translate docs*

## Modifications

*Update some doc status*

### CODE REVIEW

**Comment by SylviaBABY** [comment]
@sijia-w 你可以直接看我新提的这个 PR 上边填的描述，更改 schedule 名字的我都直接在网页上操作更改的，所以会简单一些，你可以参考一下吼

**Comment by sijia-w** [comment]
好的，多谢提醒！我在网页上一直无法修改，我换浏览器试试吧。

**Comment by SylviaBABY** [comment]
translated md:
io-flume-source 
io-hdfs2-sink 
io-hdfs3-sink 
io-influxdb-sink 
io-aerospike-sink 
io-file-source 
io-cassandra-sink 
io-cdc-debezium 
io-debezium-source 
io-rabbitmq-sink 
io-rabbitmq-source 
io-redis-sink 
io-solr-sink 
io-twitter-source
io-use

**Comment by SylviaBABY** [comment]
kafka-source
jdbc-sink
kafka-sink

**Comment by SylviaBABY** [comment]
kinesis-sink/source
mongo-sink
netty-source

**Comment by SylviaBABY** [comment]
io-debug

**Comment by Jennifer88huang** [comment]
What's the status of this PR?

**Comment by SylviaBABY** [comment]
> What's the status of this PR?

the titles above are all done, just use this PR to check out my work

**Pull request closed without merging**
